# Dark Cyberpunk Theme
COLOR_PRINTS_ACCENT_FG = "\u001b[38;5;207m"   # Neon pink
COLOR_PRINTS_ACCENT_BG = ""
COLOR_PRINTS_HIGHLIGHT_BG_FG = ""
COLOR_PRINTS_HIGHLIGHT_BG_BG = "\u001b[48;5;60m"   # Deep blue
COLOR_PRINTS_TEXT_FG = "\u001b[97m"   # Bright white
COLOR_PRINTS_TEXT_BG = ""
COLOR_PRINTS_DIM_FG = "\u001b[90m"   # Dim gray
COLOR_PRINTS_DIM_BG = ""
COLOR_PRINTS_WARNING_FG = "\u001b[33m"   # Yellow
COLOR_PRINTS_WARNING_BG = ""
COLOR_PRINTS_SUCCESS_FG = "\u001b[38;5;82m"   # Neon green
COLOR_PRINTS_SUCCESS_BG = ""
COLOR_PRINTS_ERROR_FG = "\u001b[91m"   # Bright red
COLOR_PRINTS_ERROR_BG = ""
COLOR_PRINTS_STATUS_BAR_FG = "\u001b[97m"   # White
COLOR_PRINTS_STATUS_BAR_BG = "\u001b[48;5;54m"   # Purple-blue
COLOR_PRINTS_BREADCRUMB_BAR_FG = "\u001b[38;5;51m"   # Cyan
COLOR_PRINTS_BREADCRUMB_BAR_BG = ""
COLOR_PRINTS_CHILD_HIGHLIGHT = "\u001b[38;5;81m"  # Neon blue
COLOR_PRINTS_CHILD_HIGHLIGHT_FG = "\u001b[38;5;81m"
COLOR_PRINTS_CHILD_HIGHLIGHT_BG = "\u001b[48;5;17m"  # Deep blue
COLOR_PRINTS_BLINK = "blink"
