# Matrix Theme
COLOR_PRINTS_ACCENT_FG = "\u001b[38;5;46m"   # Matrix green
COLOR_PRINTS_ACCENT_BG = ""
COLOR_PRINTS_HIGHLIGHT_BG_FG = ""
COLOR_PRINTS_HIGHLIGHT_BG_BG = "\u001b[48;5;232m"   # Black
COLOR_PRINTS_TEXT_FG = "\u001b[38;5;118m"   # Lime green
COLOR_PRINTS_TEXT_BG = ""
COLOR_PRINTS_DIM_FG = "\u001b[38;5;22m"   # Dim green
COLOR_PRINTS_DIM_BG = ""
COLOR_PRINTS_WARNING_FG = "\u001b[38;5;226m"   # Yellow
COLOR_PRINTS_WARNING_BG = ""
COLOR_PRINTS_SUCCESS_FG = "\u001b[38;5;82m"   # Bright green
COLOR_PRINTS_SUCCESS_BG = ""
COLOR_PRINTS_ERROR_FG = "\u001b[38;5;196m"   # Red
COLOR_PRINTS_ERROR_BG = ""
COLOR_PRINTS_STATUS_BAR_FG = "\u001b[38;5;46m"   # Matrix green
COLOR_PRINTS_STATUS_BAR_BG = "\u001b[48;5;232m"   # Black
COLOR_PRINTS_BREADCRUMB_BAR_FG = "\u001b[38;5;40m"   # Green
COLOR_PRINTS_BREADCRUMB_BAR_BG = ""
COLOR_PRINTS_CHILD_HIGHLIGHT = "\u001b[38;5;118m"  # Lime green
COLOR_PRINTS_CHILD_HIGHLIGHT_FG = "\u001b[38;5;118m"
COLOR_PRINTS_CHILD_HIGHLIGHT_BG = "\u001b[48;5;232m"  # Black
COLOR_PRINTS_BLINK = "blink"
