# Solarized Theme
COLOR_PRINTS_ACCENT_FG = "\u001b[38;5;136m"   # Solarized yellow
COLOR_PRINTS_ACCENT_BG = ""
COLOR_PRINTS_HIGHLIGHT_BG_FG = ""
COLOR_PRINTS_HIGHLIGHT_BG_BG = "\u001b[48;5;238m"   # Solarized base02
COLOR_PRINTS_TEXT_FG = "\u001b[38;5;244m"   # Solarized base0
COLOR_PRINTS_TEXT_BG = ""
COLOR_PRINTS_DIM_FG = "\u001b[38;5;241m"   # Solarized base01
COLOR_PRINTS_DIM_BG = ""
COLOR_PRINTS_WARNING_FG = "\u001b[38;5;166m"   # Orange
COLOR_PRINTS_WARNING_BG = ""
COLOR_PRINTS_SUCCESS_FG = "\u001b[38;5;64m"   # Green
COLOR_PRINTS_SUCCESS_BG = ""
COLOR_PRINTS_ERROR_FG = "\u001b[38;5;124m"   # Red
COLOR_PRINTS_ERROR_BG = ""
COLOR_PRINTS_STATUS_BAR_FG = "\u001b[38;5;230m"   # Solarized base2
COLOR_PRINTS_STATUS_BAR_BG = "\u001b[48;5;136m"   # Solarized yellow
COLOR_PRINTS_BREADCRUMB_BAR_FG = "\u001b[38;5;160m"   # Solarized red
COLOR_PRINTS_BREADCRUMB_BAR_BG = "\u001b[48;5;238m"   # Solarized base02
COLOR_PRINTS_CHILD_HIGHLIGHT = "\u001b[38;5;37m"   # Solarized blue (legacy)
COLOR_PRINTS_CHILD_HIGHLIGHT_FG = "\u001b[38;5;166m"   # Solarized red
COLOR_PRINTS_CHILD_HIGHLIGHT_BG = "\u001b[48;5;238m"   # Solarized base02
COLOR_PRINTS_BLINK = "blink"
