# Pastel Rainbow Theme
COLOR_PRINTS_ACCENT_FG = "\u001b[38;5;218m"   # Pink
COLOR_PRINTS_ACCENT_BG = ""
COLOR_PRINTS_HIGHLIGHT_BG_FG = ""
COLOR_PRINTS_HIGHLIGHT_BG_BG = "\u001b[48;5;195m"   # Light magenta
COLOR_PRINTS_TEXT_FG = "\u001b[38;5;159m"   # Light blue
COLOR_PRINTS_TEXT_BG = ""
COLOR_PRINTS_DIM_FG = "\u001b[38;5;188m"   # Light yellow
COLOR_PRINTS_DIM_BG = ""
COLOR_PRINTS_WARNING_FG = "\u001b[38;5;221m"   # Pastel yellow
COLOR_PRINTS_WARNING_BG = ""
COLOR_PRINTS_SUCCESS_FG = "\u001b[38;5;157m"   # Pastel green
COLOR_PRINTS_SUCCESS_BG = ""
COLOR_PRINTS_ERROR_FG = "\u001b[38;5;210m"   # Pastel red
COLOR_PRINTS_ERROR_BG = ""
COLOR_PRINTS_STATUS_BAR_FG = "\u001b[38;5;195m"   # Light magenta
COLOR_PRINTS_STATUS_BAR_BG = "\u001b[48;5;159m"   # Light blue
COLOR_PRINTS_BREADCRUMB_BAR_FG = "\u001b[38;5;159m"   # Light blue
COLOR_PRINTS_BREADCRUMB_BAR_BG = ""
COLOR_PRINTS_CHILD_HIGHLIGHT = "\u001b[38;5;159m"  # Pastel blue
COLOR_PRINTS_CHILD_HIGHLIGHT_FG = "\u001b[38;5;159m"
COLOR_PRINTS_CHILD_HIGHLIGHT_BG = "\u001b[48;5;195m"  # Pastel magenta
COLOR_PRINTS_BLINK = "blink"
