# To create a Homebrew tap, you'll need to:
# 1. Create a repository named "homebrew-tap" in your GitHub account
# 2. Add this formula to that repository

class Mdbub < Formula
  desc "Terminal-first interactive mindmap CLI tool"
  homepage "https://github.com/collabinator/mdbubbles"
  url "https://github.com/collabinator/mdbubbles/archive/refs/tags/v0.3.0.tar.gz"
  sha256 "REPLACE_WITH_ACTUAL_SHA256" # updated automatically by GitHub Actions
  license "Apache-2.0"
  head "https://github.com/collabinator/mdbubbles.git", branch: "main"

  depends_on "python@3.11"

  # Python dependencies are dynamically generated by CI and included here
  # See .github/workflows/release.yml for the update-python-dependencies job
  instance_eval(File.read(File.expand_path("../mdbub_resources.rb", __FILE__)))

  def install
    virtualenv_install_with_resources
  end

  test do
    system "#{bin}/mdbub", "version"
  end
end
