name: Update Python Dependencies for Homebrew

on:
  workflow_dispatch:
  push:
    paths:
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/update-python-dependencies.yml'

jobs:
  update-python-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tap repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/homebrew-tap
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: tap-repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install homebrew-pypi-poet
        run: |
          pip install homebrew-pypi-poet

      - name: Generate Homebrew resource blocks
        run: |
          poet click markdown markdown-it-py packaging platformdirs prompt-toolkit pyyaml requests rich rich-click ruamel.yaml tomli typer \
            > tap-repo/Formula/mdbub_resources.rb

      - name: Commit and push changes
        run: |
          cd tap-repo
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add Formula/mdbub_resources.rb
          git commit -m "Update Python dependencies for mdbub formula"
          git push
